SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE   PROCEDURE [dbo].[SP_EmployeeFinalLoad] 

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	INSERT INTO M_EC_LOG_DW2_EMPLOYEE 
		SELECT 
			   [Result Set]
      ,[Match Found]
      ,[Employee ID]
      ,[Person ID]
      ,[User ID]
      ,[Username]
      ,[User Account]
      ,[Sequence Number]
      ,[Hierarchy]
      ,[Hierarchy Level]
      ,[DS Number]
      ,[Email]
      ,[Email Address]
      ,[User Full Name]
      ,[User First Name]
      ,[User Last Name]
      ,[Display Name]
      ,[First Name]
      ,[Middle Name]
      ,[Last Name]
      ,[Display Name Kanji]
      ,[First Name Kanji]
      ,[Middle Name Kanji]
      ,[Last Name Kanji]
      ,[Display Name Kana]
      ,[First Name Kana]
      ,[Middle Name Kana]
      ,[Last Name Kana]
      ,[IF Formal Last Name]
      ,[IF Formal First Name]
      ,[IF Formal Middle Name]
      ,[IF Formal Last Name Kanji]
      ,[IF Formal First Name Kanji]
      ,[IF Formal Last Name Kana]
      ,[IF Formal First Name Kana]
      ,[Title]
      ,[Suffix]
      ,[Gender]
      ,[Business Phone Country Code]
      ,[Business Phone Number]
      ,[Business Phone Extension]
      ,[Business Phone VOIP]
      ,[Mobile Phone Country Code]
      ,[Mobile Phone Number]
      ,[Mobile Phone Extension]
      ,[Mobile Phone VOIP]
      ,[Fax Country Code]
      ,[Fax Number]
      ,[Fax Extension]
      ,[Fax VOIP]
      ,[Cost Center]
      ,[Cost Center Name]
      ,[Job Cost Center]
      ,[Job Cost Center Code]
      ,[Job Cost Center Name]
      ,[Location Code]
      ,[Location]
      ,[Location Name]
      ,[Company Country]
      ,[Company Code]
      ,[Legal Entity ID]
      ,[Company]
      ,[Company Name]
      ,[Group Region]
      ,[Timezone]
      ,[User Timezone]
      ,[Local Employee Number]
      ,[Local Job Grade]
      ,[Local Job Title]
      ,[Global Job Grade]
      ,[Global Job Title Code]
      ,[Global Job Title]
      ,[Job Title]
      ,[Unit Code]
      ,[Unit Name]
      ,[Unit]
      ,[Division Code]
      ,[Division Name]
      ,[Division]
      ,[Department Code]
      ,[Department Name]
      ,[Department]
      ,[Section Code]
      ,[Section Name]
      ,[Section]
      ,[Solid Line Manager User ID]
      ,[Manager Employee ID]
      ,[Manager User ID]
      ,[Manager Username]
      ,[Manager DS Number]
      ,[Manager Email]
      ,[Manager Full Name]
      ,[Manager First Name]
      ,[Manager Last Name]
      ,[Manager isPrimary]
      ,[Manager Status Code]
      ,[Direct Reports]
      ,[Total Team Size]
      ,[Function Name]
      ,[Function Head Employee ID]
      ,[Function Head DS Number]
      ,[Function Head Email]
      ,[Function Head Name]
      ,[Function Head Global Unit]
      ,[Function Head Global Division]
      ,[Login Type]
      ,[Status Code]
      ,[Employee Status Code]
      ,[Employee Status Option ID]
      ,[Assignment Type Code]
      ,[Assignment Type]
      ,[Employment Assignment Type]
      ,[isPrimaryMerged]
      ,[Employment Classification Code]
      ,[Employment Classification]
      ,[Employee Type Code]
      ,[Employee Type]
      ,[Employment Type Code]
      ,[Employment Type]
      ,[Employment Type Japanese]
      ,[Employment Details Notes]
      ,[Job Info Notes]
      ,[Event]
      ,[Event Reason Code]
      ,[Event Reason]
      ,[Leave of Absence Reason]
      ,[Birth Date]
      ,[Hire Date]
      ,[Start Date]
      ,[Original Start Date]
      ,[Service Date]
      ,[Last Inactivation Date]
      ,[Legal Retirement Date]
      ,[Last Date Worked]
      ,[Payroll End Date]
      ,[Termination Date]
      ,[Job Termination Date]
      ,[Created Date]
      ,[User Last Modified Date]
      ,[Job Last Modified Date]
      ,[Employment Last Modified Date]
      ,[Biographic Last Modified Date]
      ,[Personal Last Modified Date]
		  FROM [ANALYSIS_LOG].[dbo].[M_EC_LOG_DW2_EMPLOYEEINFO_EMPLOYEESOURCE]
 
      	  WHERE [Employee ID] IS NOT NULL
END

GO
