IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'RENESAS-DOMAIN\G_REL-HQ-BI-10002')
CREATE LOGIN [RENESAS-DOMAIN\G_REL-HQ-BI-10002] FROM WINDOWS
GO
CREATE USER [RENESAS-DOMAIN\G_REL-HQ-BI-10002] FOR LOGIN [RENESAS-DOMAIN\G_REL-HQ-BI-10002]
GO
