CREATE TABLE [dbo].[REST_API_TEST_2]
(
[P_dir_id] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_name] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_agreement_description] [nvarchar] (max) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_counterparty_nda_provided] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_department] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_description_customer_distr_sales] [nvarchar] (4000) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_description_services] [nvarchar] (4000) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_language_selector] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_legal_reviewer] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_licensing_description] [nvarchar] (4000) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_licensing_type] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_location_of_requester] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_new_primary_followup_contact_email] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_new_primary_followup_contact_name] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_new_vendor_name] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_principal_inventor_contact_selectable] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_principal_inventor_poc_list] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_project_description_nda] [nvarchar] (4000) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_renesas_poc_list] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_request_category] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_request_date] [datetime] NULL,
[P_data_p_type_agreement] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_type_of_vendor_agreement] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_p_yes_own_derivative] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_requester_email] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_requester_name] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_id] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_success] [bit] NULL,
[P_count] [bigint] NULL,
[ id] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[__FileName] [nvarchar] (600) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_name] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_prefixed_name] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
