CREATE TABLE [dbo].[T_BI_LOG_DW2_CUBESLOG_old]
(
[FIELDNAME] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL,
[TRANSACTIONDATE] [date] NULL,
[DATABASENAME] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL,
[RECORDCOUNT] [int] NULL,
[EMAILID] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL,
[APPLICATION NAME] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[LOGIN TYPE] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
