CREATE TABLE [dbo].[TPRC_LOGM_EX_USERTYPES]
(
[Id] [int] NOT NULL,
[User Type] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPRC_LOGM_EX_USERTYPES] ADD CONSTRAINT [PK_lkpUnifiedAuditLogPBIUserType] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
