CREATE TABLE [dbo].[T_CQ_LOG_DW2_RAINBOWSEARCHCONDITIONINFO]
(
[DATANAME] [nvarchar] (300) COLLATE Japanese_XJIS_100_BIN2 NULL,
[TABLE_NAME] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[COLUMN_NAME] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[COLUMN_ID] [float] NULL
) ON [PRIMARY]
GO
