CREATE TABLE [dbo].[T_CQ_LOG_DW2_RAINBOWDISPLAYACCESS]
(
[SQLID] [int] NOT NULL,
[ACCESSDATE] [datetime] NOT NULL,
[USERID] [nchar] (16) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[SCREENID] [int] NOT NULL,
[COMPONENTNAME] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[FUNCTIONNAME] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[SYSTEMID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_CQ_LOG_DW2_RAINBOWDISPLAYACCESS] ADD CONSTRAINT [PK_tblDispAccessLog1] PRIMARY KEY CLUSTERED  ([SQLID], [ACCESSDATE], [USERID], [SCREENID]) ON [PRIMARY]
GO
