CREATE TABLE [dbo].[M_EC_LOG_DW2_EMPLOYEEINFO_TEST]
(
[User ID] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Username] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Full Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[First Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Last Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Email] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DS Number] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DS ID Number] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Global Job Grade] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Global Job Title] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Local Job Grade] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Local Job Title] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Location Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Group Region] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Global Unit Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Global Division Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Unit Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Unit Name Abbreviation] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Division Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Department Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Section Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager User ID] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager Username] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager Full Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager First Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager Last Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager Email] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager DS Number] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager DS ID Number] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Direct Reports] [int] NULL,
[TotalTeamSize] [int] NULL,
[Status] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Status Code] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Is Primary] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Employee Type] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Employment Type] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Employment Type Japanese] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Assignment Type] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Last Inactivation Date] [datetime] NULL,
[Termination Date] [datetime] NULL,
[Last Modified Date] [datetime] NULL,
[Created Date] [datetime] NULL,
[Hierarchy Level] [nvarchar] (1024) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Global Unit] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Global Unit Code] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Global Division] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Global Division Code] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Hierarchy] [nvarchar] (2048) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Function Head DS ID] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Function Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Function Head Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Function Head Global Unit] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Function Head Global Division] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Function Head Email] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Login Type] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Location] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Location Code] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Unit] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Unit Code] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Unit Short Name] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Division] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Division Code] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Department] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Department Code] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Section] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Regional Section Code] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager Is Primary] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager Status] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager Status Code] [nvarchar] (64) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
