CREATE TABLE [dbo].[M_BC_LOG_DW2_USERS]
(
[ID] [nvarchar] (255) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[USERNAME] [nvarchar] (255) COLLATE Japanese_XJIS_100_BIN2 NULL,
[LASTNAME] [nvarchar] (255) COLLATE Japanese_XJIS_100_BIN2 NULL,
[FIRSTNAME] [nvarchar] (255) COLLATE Japanese_XJIS_100_BIN2 NULL,
[NAME] [nvarchar] (255) COLLATE Japanese_XJIS_100_BIN2 NULL,
[EMAIL] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[M_BC_LOG_DW2_USERS] ADD CONSTRAINT [PK_tblBambooUserInfo] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
