CREATE TABLE [dbo].[M_EC_LOG_DW2_LDAP]
(
[UID] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[ManagerUID] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ManagerEmail] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Hierarchy] [nvarchar] (2048) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Employeenumber] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrcompanycode] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrdivisioncode] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrorganizationcode] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashremployeegroup] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrworkingsituation] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashremployeementstatus] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrcompanyname] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrdivisionname] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrorganizationsymbolfullname] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Title] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrjobcode] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrsendingcompanycode] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrsendingcompanyname] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesassnflag] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[SN] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Givenname] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesassnkana] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesasgivennamekana] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesaslockstatus] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Mailhost] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Mailroutingaddress] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Email] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Manager] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrcompanyname_lang-ja-jp] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesashrdivisionname_lang-ja-jp] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[renesashrorgasymbolfullname_lang-ja-jp] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Title_lang-ja-jp] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[SN_lang-ja-jp] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Givenname_lang-ja-jp] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesassnkana_lang-ja-jp] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Renesasgivennamekana_lang-ja-jp] [nvarchar] (512) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Createtimestamp] [nvarchar] (1024) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Modifytimestamp] [nvarchar] (1024) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Unit] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Unit Code] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Unit Name] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Division] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Division Code] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL,
[Division Name] [nvarchar] (256) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[M_EC_LOG_DW2_LDAP] ADD CONSTRAINT [PK_M_EC_LOG_DW2_LDAP] PRIMARY KEY CLUSTERED  ([UID]) ON [PRIMARY]
GO
