CREATE TABLE [dbo].[T_BI_LOG_DW2_SSASMDEXTENDEDEVENTS]
(
[EventClass] [int] NULL,
[AttachActibityID] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[AttachActibityIDXfer] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ApplicationName] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ClientProcessID] [int] NULL,
[ConnectionID] [int] NULL,
[CurrentTime] [datetime] NULL,
[DatabaseName] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[EventSubclass] [int] NULL,
[NTCanonicalUserName] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[NTDomainName] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[NTUserName] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[RequestID] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[RequestParameters] [nvarchar] (max) COLLATE Japanese_XJIS_100_BIN2 NULL,
[RequestProperties] [nvarchar] (max) COLLATE Japanese_XJIS_100_BIN2 NULL,
[SPID] [int] NULL,
[ServerName] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[SessionID] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[StartTime] [datetime] NULL,
[TextData] [nvarchar] (max) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CPUTime] [bigint] NULL,
[Duration] [bigint] NULL,
[EndTime] [datetime] NULL,
[Error] [int] NULL,
[ErrorType] [int] NULL,
[IntegerData] [bigint] NULL,
[Severity] [int] NULL,
[Success] [int] NULL,
[CalculationExpression] [nvarchar] (max) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ClientHostName] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[SessionType] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[SYSTEMID] [int] NULL
) ON [PRIMARY]
GO
