CREATE TABLE [dbo].[REST_API_TEST1]
(
[__FileName] [nvarchar] (600) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_id] [nvarchar] (96) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_success] [bit] NULL,
[P_data.atom_properties_allow_custom_text] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_allow_duplicates] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_allow_grid_popup] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_atom_dictionary_id] [nvarchar] (96) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_atom_dictionary_type] [nvarchar] (56) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_available_to_word_addin] [bit] NULL,
[P_data.atom_properties_calculated] [bit] NULL,
[P_data.atom_properties_calculation_type] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_cascade_delete] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_combo_data_source] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_created_at] [datetime] NULL,
[P_data.atom_properties_currency_code] [nvarchar] (12) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_data_type] [nvarchar] (32) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_deleted_at] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_description] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_disable_dashboard_summary] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_display_name] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_display_on_dashboard] [bit] NULL,
[P_data.atom_properties_enforce_app_type] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_expression] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_filter_column] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_highly_confidential_information] [bit] NULL,
[P_data.atom_properties_index_in_warehouse] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_initial_value] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_length_in_warehouse] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_list] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_min_chars] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_name] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_numeric_calc_type] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_olap_cube] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_order] [bigint] NULL,
[P_data.atom_properties_parent_filter_fields] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_parent_filter_id] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_parent_filter_result_fields] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_personal_health_information] [bit] NULL,
[P_data.atom_properties_personally_identifiable_information] [bit] NULL,
[P_data.atom_properties_radio_button] [bit] NULL,
[P_data.atom_properties_radio_button_columns] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_readonly_field] [bit] NULL,
[P_data.atom_properties_related_atoms_app] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_related_inverse_field] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_render_as_buttons] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_required] [bit] NULL,
[P_data.atom_properties_search_column] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_search_facet] [bit] NULL,
[P_data.atom_properties_search_result] [bit] NULL,
[P_data.atom_properties_skip_empty_panel] [bit] NULL,
[P_data.atom_properties_skip_panel] [bit] NULL,
[P_data.atom_properties_skip_render] [bit] NULL,
[P_data.atom_properties_tags] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_ui_action_id] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_updated_at] [datetime] NULL,
[P_data.atom_properties_validate_case_sensitive] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_validate_unique] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_validate_unique_filter_id] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_validate_unique_scope] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_validator_id] [nvarchar] (1020) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_value_column] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_values] [nvarchar] (80) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data.atom_properties_prefixed_name] [nvarchar] (88) COLLATE Japanese_XJIS_100_BIN2 NULL,
[P_data_name] [nvarchar] (48) COLLATE Japanese_XJIS_100_BIN2 NULL,
[_id] [nvarchar] (96) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
