CREATE TABLE [dbo].[M_CQ_LOG_DW2_RAINBOWSCREENMASTER]
(
[SCREENID] [numeric] (4, 0) NOT NULL,
[SCREENNAME] [nvarchar] (60) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[SCREENDIV] [nvarchar] (2) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[SEQNO] [nvarchar] (10) COLLATE Japanese_XJIS_100_BIN2 NOT NULL
) ON [PRIMARY]
GO
