ALTER ROLE [db_owner] ADD MEMBER [GBI00001]
GO
ALTER ROLE [db_owner] ADD MEMBER [RENESAS-DOMAIN\a5091058]
GO
ALTER ROLE [db_owner] ADD MEMBER [RENESAS-DOMAIN\G_REL-HQ-BI-10002]
GO
ALTER ROLE [db_owner] ADD MEMBER [Sai.Prathuru@renesas.com]
GO
