CREATE TABLE [dbo].[T_GPR_MM_DW1_EPR_EPR_ADDITION_APPR]
(
[EPR_EPR_MASTER_ID] [int] NULL,
[EPR_ADDITION_APPR] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CREATED_DATE] [datetime2] NULL,
[MODIFIED_DATE] [datetime2] NULL
) ON [PRIMARY]
GO
