CREATE TABLE [dbo].[M_GPR_MM_DW2_CFG_COMPANY_MASTER]
(
[CFG_COMPANY_MASTER_ID] [int] NOT NULL,
[COMPANY_CODE] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[COMPANY_NAME] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[COMPANY_DESCRIPTION] [nvarchar] (1000) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DEFAULT_PURCHASING_ORG] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DEFAULT_CURRENCY_NAME] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ACTIVE] [nvarchar] (3) COLLATE Japanese_XJIS_100_BIN2 NULL,
[APR_COMPANY_GROUP] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[IF_COMPANY_CODE] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[IF_DESTINATION_SYSTEM] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DEFAULT_TIMEZONE] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DEFAULT_DISP_TIME_FORMAT] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DEFAULT_DISP_DATE_FORMAT] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DEFAULT_DISP_DATETIME_FORMAT] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DEFAULT_PR_NOTIFY_EMAIL] [nvarchar] (1000) COLLATE Japanese_XJIS_100_BIN2 NULL,
[DEFAULT_LANGUAGE] [nvarchar] (3) COLLATE Japanese_XJIS_100_BIN2 NULL,
[INSERTDATETIME] [datetime] NULL,
[UPDATEDATETIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[M_GPR_MM_DW2_CFG_COMPANY_MASTER] ADD CONSTRAINT [PK_M_GPR_MM_DW2_CFG_COMPANY_MASTER] PRIMARY KEY CLUSTERED  ([CFG_COMPANY_MASTER_ID]) ON [PRIMARY]
GO
