CREATE TABLE [dbo].[T_GPR_MM_DW2_R14_R14_MASTER]
(
[R14_R14_MASTER_ID] [int] NOT NULL,
[R14_NUMBER] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[R14_STATUS] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[R14_R14_ITEM] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[COMPANY_CODE] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[R14_INITIATOR] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[R14_INITIATE_DATE] [datetime2] NULL,
[R14_REQUESTOR] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[R14_TITLE] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[R14_DETAIL] [nvarchar] (4000) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CPX_NUMBER] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CURRENCY_NAME] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[R14_BUDGET_AMOUNT] [money] NULL,
[R14_ANTI_BRIBERY] [nvarchar] (3) COLLATE Japanese_XJIS_100_BIN2 NULL,
[R14_FINAL_APPROVAL_DEADLINE] [datetime2] NULL,
[CURRENCY_RATE] [money] NULL,
[CREATED_DATE] [datetime2] NULL,
[MODIFIED_DATE] [datetime2] NULL,
[INSERTDATETIME] [datetime] NULL,
[UPDATEDATETIME] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_GPR_MM_DW2_R14_R14_MASTER] ADD CONSTRAINT [PK_T_GPR_MM_DW2_R14_R14_MASTER] PRIMARY KEY CLUSTERED  ([R14_R14_MASTER_ID]) ON [PRIMARY]
GO
