CREATE TABLE [dbo].[M_GPR_LOG_DW2_EXECUTION]
(
[INTERFACE_TABLE_NAME] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL,
[LAST_RECORD_DATETIME] [datetime2] NULL,
[LAST_RECORD_ID] [int] NULL,
[LAST_EXECUTED_BY] [nvarchar] (128) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
