CREATE TABLE [dbo].[M_GPR_MM_DW1_CFG_CPX_MASTER]
(
[CFG_CPX_MASTER_ID] [int] NULL,
[CPX_NUMBER] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CPX_DESCRIPTION] [nvarchar] (1000) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CPX_YEAR] [char] (4) COLLATE Japanese_XJIS_100_BIN2 NULL,
[COMPANY_CODE] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ACTIVE] [char] (3) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CURRENCY_NAME] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CPX_BUDGET_AMOUNT] [money] NULL,
[CFG_COST_CENTER_NAME] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CPX_EQUIP_JIGTOOL] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CPX_APPROVAL_TARGET] [datetime] NULL
) ON [PRIMARY]
GO
