CREATE TABLE [dbo].[T_GPR_MM_DW1_ATTACHMENTS]
(
[ATTACHMENTS_ID] [int] NULL,
[ATTACHMENT_DOCUMENT_TYPE] [nvarchar] (20) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ATTACHMENT_DOCUMENT_ID] [int] NULL,
[ATTACHMENT_ACTUAL_FILE_NAME] [nvarchar] (200) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ATTACHMENT_SYSTEM_FILE_NAME] [nvarchar] (300) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ATTACHMENT_FOLDER_PATH] [nvarchar] (400) COLLATE Japanese_XJIS_100_BIN2 NULL,
[ATTACHMENT_TYPE] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CREATED_DATE] [datetime2] NULL,
[MODIFIED_DATE] [datetime2] NULL
) ON [PRIMARY]
GO
