CREATE TABLE [dbo].[T_GPR_MM_DW2_EPR_EPR_ADDITION_APPR]
(
[EPR_EPR_MASTER_ID] [int] NOT NULL,
[EPR_ADDITION_APPR] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NOT NULL,
[CREATED_DATE] [datetime2] NULL,
[MODIFIED_DATE] [datetime2] NULL,
[INSERTDATETIME] [datetime] NULL,
[UPDATEDATETIME] [datetime] NULL,
[DELETE_FLAG] [nvarchar] (3) COLLATE Japanese_XJIS_100_BIN2 NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_GPR_MM_DW2_EPR_EPR_ADDITION_APPR] ADD CONSTRAINT [PK_T_GPR_MM_DW2_EPR_EPR_ADDITION_APR] PRIMARY KEY CLUSTERED  ([EPR_EPR_MASTER_ID], [EPR_ADDITION_APPR]) ON [PRIMARY]
GO
