CREATE TABLE [dbo].[T_GPR_MM_DW1_EPR_CC_REQUEST_TO]
(
[EPR_EPR_MASTER_ID] [int] NULL,
[EPR_CC_REQUEST_TO] [nvarchar] (100) COLLATE Japanese_XJIS_100_BIN2 NULL,
[CREATED_DATE] [datetime2] NULL,
[MODIFIED_DATE] [datetime2] NULL
) ON [PRIMARY]
GO
