SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE        PROCEDURE [dbo].[SP_Update_EPR_EPR_REVIEW]
(@EPR_EPR_REVIEW_ID INT,
@EPR_EPR_MASTER_ID INT,
@EPR_CLOSURE_TYPE NVARCHAR(100),
@EPR_CLOSURE_REMARK NVARCHAR(1000),
@EPR_REVIEW_TYPE NVARCHAR(100),
@EPR_CLOSURE_BY NVARCHAR(20),
@EPR_CLOSURE_DATE DATETIME2(7),
@UPDATEDATETIME	DATETIME,
@MODIFIED_DATE DATETIME2(7),

@DDW2_UPDATE_TIME DATETIME,
@DELETE_FLAG NVARCHAR(3),
@DW			INT
)
	  
AS

BEGIN

SET NOCOUNT ON;

	IF @DW=2 
		BEGIN
				UPDATE dbo.T_GPR_MM_DW2_EPR_EPR_REVIEW
				SET
				EPR_CLOSURE_TYPE 	=@EPR_CLOSURE_TYPE,
				EPR_CLOSURE_REMARK 	=@EPR_CLOSURE_REMARK,
				EPR_REVIEW_TYPE 	=@EPR_REVIEW_TYPE,
				EPR_CLOSURE_BY 	=@EPR_CLOSURE_BY,
				EPR_CLOSURE_DATE 	=@EPR_CLOSURE_DATE ,
				UPDATEDATETIME	=@UPDATEDATETIME,
				MODIFIED_DATE=@MODIFIED_DATE,
				DELETE_FLAG=@DELETE_FLAG
				
				WHERE EPR_EPR_REVIEW_ID= @EPR_EPR_REVIEW_ID AND EPR_EPR_MASTER_ID=@EPR_EPR_MASTER_ID
		END



	IF @DW=3 
		BEGIN
				UPDATE dbo.T_GPR_MM_DW3_EPR_EPR_REVIEW
				SET
				EPR_CLOSURE_TYPE 	=@EPR_CLOSURE_TYPE,
				EPR_CLOSURE_REMARK 	=@EPR_CLOSURE_REMARK,
				EPR_REVIEW_TYPE 	=@EPR_REVIEW_TYPE,
				EPR_CLOSURE_BY 	=@EPR_CLOSURE_BY,
				EPR_CLOSURE_DATE 	=@EPR_CLOSURE_DATE ,
				UPDATEDATETIME	=@UPDATEDATETIME,
				MODIFIED_DATE=@MODIFIED_DATE,
				DELETE_FLAG=@DELETE_FLAG,
				DW2_UPDATE_TIME=@DDW2_UPDATE_TIME
				WHERE EPR_EPR_REVIEW_ID= @EPR_EPR_REVIEW_ID AND EPR_EPR_MASTER_ID=@EPR_EPR_MASTER_ID
		END
END
GO
