SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE       PROCEDURE [dbo].[SP_Update_R14_R14_MASTER]
(@R14_R14_MASTER_ID INT,
@R14_NUMBER NVARCHAR(20 ),
@R14_STATUS NVARCHAR(100 ),
@R14_R14_ITEM NVARCHAR(100 ),
@COMPANY_CODE NVARCHAR(20 ),
@R14_INITIATOR NVARCHAR(100 ),
@R14_INITIATE_DATE DATETIME2(7),
@R14_REQUESTOR NVARCHAR(100 ),
@R14_TITLE NVARCHAR(100 ),
@R14_DETAIL NVARCHAR(4000 ),
@CPX_NUMBER NVARCHAR(100 ),
@CURRENCY_NAME NVARCHAR(20 ),
@R14_BUDGET_AMOUNT MONEY,
@R14_ANTI_BRIBERY NVARCHAR(3),
@R14_FINAL_APPROVAL_DEADLINE DATETIME2(7),
@CURRENCY_RATE money,
@CREATED_DATE DATETIME2(7),
@MODIFIED_DATE DATETIME2(7),
@UPDATEDATETIME DATETIME,
@DW             INT

)
	  
AS

BEGIN

SET NOCOUNT ON;

	IF @DW=2
		BEGIN
			UPDATE dbo.T_GPR_MM_DW2_R14_R14_MASTER

			SET R14_R14_MASTER_ID	=	@R14_R14_MASTER_ID,
			R14_NUMBER	=	@R14_NUMBER,
			R14_STATUS	=	@R14_STATUS		,
			R14_R14_ITEM	=@R14_R14_ITEM		,
			COMPANY_CODE	=@COMPANY_CODE		,
			R14_INITIATOR	=	@R14_INITIATOR		,
			R14_INITIATE_DATE	=	@R14_INITIATE_DATE		,
			R14_REQUESTOR	=	@R14_REQUESTOR		,
			R14_TITLE	=	@R14_TITLE		,
			R14_DETAIL	=	@R14_DETAIL		,
			CPX_NUMBER	=	@CPX_NUMBER		,
			CURRENCY_NAME	=	@CURRENCY_NAME		,
			R14_BUDGET_AMOUNT	=	@R14_BUDGET_AMOUNT,
			R14_ANTI_BRIBERY	=	@R14_ANTI_BRIBERY,
			R14_FINAL_APPROVAL_DEADLINE	=	@R14_FINAL_APPROVAL_DEADLINE,
			CURRENCY_RATE	=	@CURRENCY_RATE		,
			CREATED_DATE	=	@CREATED_DATE		,
			MODIFIED_DATE	=	@MODIFIED_DATE		,
			UPDATEDATETIME	=	@UPDATEDATETIME		
		
			WHERE R14_R14_MASTER_ID = @R14_R14_MASTER_ID  
		END
	IF @DW=3 
		BEGIN
			UPDATE dbo.T_GPR_MM_DW3_R14_R14_MASTER

			SET R14_R14_MASTER_ID	=	@R14_R14_MASTER_ID,
			R14_NUMBER	=	@R14_NUMBER,
			R14_STATUS	=	@R14_STATUS		,
			R14_R14_ITEM	=@R14_R14_ITEM		,
			COMPANY_CODE	=@COMPANY_CODE		,
			R14_INITIATOR	=	@R14_INITIATOR		,
			R14_INITIATE_DATE	=	@R14_INITIATE_DATE		,
			R14_REQUESTOR	=	@R14_REQUESTOR		,
			R14_TITLE	=	@R14_TITLE		,
			R14_DETAIL	=	@R14_DETAIL		,
			CPX_NUMBER	=	@CPX_NUMBER		,
			CURRENCY_NAME	=	@CURRENCY_NAME		,
			R14_BUDGET_AMOUNT	=	@R14_BUDGET_AMOUNT,
			R14_ANTI_BRIBERY	=	@R14_ANTI_BRIBERY,
			R14_FINAL_APPROVAL_DEADLINE	=	@R14_FINAL_APPROVAL_DEADLINE,
			CURRENCY_RATE	=	@CURRENCY_RATE		,
			CREATED_DATE	=	@CREATED_DATE		,
			MODIFIED_DATE	=	@MODIFIED_DATE		,
			UPDATEDATETIME	=	@UPDATEDATETIME		


			WHERE R14_R14_MASTER_ID = @R14_R14_MASTER_ID  
		END



END
GO
