SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE          PROCEDURE [dbo].[SP_Update_R14_R14_CC_REQUEST_TO]
(@R14_R14_MASTER_ID INT,
@R14_CC_REQUEST_TO NVARCHAR(100),
@UPDATEDATETIME	DATETIME,
@MODIFIED_DATE  DATETIME2(7),
@DDW2_UPDATE_TIME DATETIME,
@DELETE_FLAG    NVARCHAR(3),
@CREATED_DATE DATETIME2(7),
@DW				INT
)
	  
AS

BEGIN

SET NOCOUNT ON;

	IF @DW=2 
		BEGIN
				UPDATE dbo.T_GPR_MM_DW2_R14_R14_CC_REQUEST_TO
				SET
				R14_CC_REQUEST_TO 	=@R14_CC_REQUEST_TO,
				UPDATEDATETIME	=@UPDATEDATETIME,
				MODIFIED_DATE=@MODIFIED_DATE,
				CREATED_DATE    =@CREATED_DATE,
				DELETE_FLAG=@DELETE_FLAG
				WHERE R14_R14_MASTER_ID = @R14_R14_MASTER_ID  AND R14_CC_REQUEST_TO=@R14_CC_REQUEST_TO
		END

	IF @DW=3 
		BEGIN
				UPDATE dbo.T_GPR_MM_DW3_R14_R14_CC_REQUEST_TO
				SET
				R14_CC_REQUEST_TO 	=@R14_CC_REQUEST_TO,
				UPDATEDATETIME	=@UPDATEDATETIME,
				MODIFIED_DATE=@MODIFIED_DATE,
				CREATED_DATE    =@CREATED_DATE,
				DELETE_FLAG=@DELETE_FLAG,
				DW2_UPDATE_TIME=@DDW2_UPDATE_TIME
				WHERE R14_R14_MASTER_ID = @R14_R14_MASTER_ID  AND R14_CC_REQUEST_TO=@R14_CC_REQUEST_TO
		END
END
GO
