SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE          PROCEDURE [dbo].[SP_Update_EPR_CC_REQUEST_TO]
(@EPR_EPR_MASTER_ID INT,
@EPR_CC_REQUEST_TO NVARCHAR(100),
@UPDATEDATETIME	DATETIME,
@MODIFIED_DATE  DATETIME2(7),
@DDW2_UPDATE_TIME DATETIME,
@DELETE_FLAG NVARCHAR(3),
@CREATED_DATE DATETIME2(7),
@DW				INT)
	  
AS

BEGIN

SET NOCOUNT ON;

	IF @DW=2
		BEGIN
			UPDATE dbo.T_GPR_MM_DW2_EPR_CC_REQUEST_TO
			SET
			EPR_CC_REQUEST_TO 	=@EPR_CC_REQUEST_TO,
			UPDATEDATETIME	=@UPDATEDATETIME,
			MODIFIED_DATE=@MODIFIED_DATE,
			CREATED_DATE=@CREATED_DATE,
				DELETE_FLAG=@DELETE_FLAG
			WHERE EPR_EPR_MASTER_ID = @EPR_EPR_MASTER_ID  AND EPR_CC_REQUEST_TO=@EPR_CC_REQUEST_TO
		END

		IF @DW=3
		BEGIN
			UPDATE dbo.T_GPR_MM_DW3_EPR_CC_REQUEST_TO
			SET
			EPR_CC_REQUEST_TO 	=@EPR_CC_REQUEST_TO,
			UPDATEDATETIME	=@UPDATEDATETIME,
			MODIFIED_DATE=@MODIFIED_DATE,
			CREATED_DATE=@CREATED_DATE,
			DELETE_FLAG=@DELETE_FLAG,
				DW2_UPDATE_TIME=@DDW2_UPDATE_TIME
			WHERE EPR_EPR_MASTER_ID = @EPR_EPR_MASTER_ID  AND EPR_CC_REQUEST_TO=@EPR_CC_REQUEST_TO
		END

END
GO
